PingpongOS:
	gcc -o PINGPONG pingpong-mqueue.c pingpong.c queue.c -g -lm

debug:
	gcc -Wall -DDEBUG -o PINGPONG pingpong-mqueue.c pingpong.c queue.c -g -lm
	
all:
	gcc -Wall -o PINGPONG pingpong-mqueue.c pingpong.c queue.c -g -lm
